
# Core tox configuration
[tox]

# A list of environments that will be run by default when running tox without specifying any environment
env_list =
    py310
    py311
    py312
    py313
    coverage
    pylint
    pycodestyle
    pydoclint
    mypy
    docs

# Base configuration for test environments that tox will fallback to for missing values; this avoids having to repeat the same configuration for the
# unit test environments py310, py311, py312, and py313 over and over again; it first builds the frontend (this is required for the unit tests to run,
# because they test if the frontend can be served via the backend for which the frontend build output is required) and then runs the unit tests for
# the backend REST API with the corresponding Python version; to build the frontend, the NPM package manager is whitelisted, as tox does not allow the
# use of binaries from outside the virtual environment by default
[testenv]
uv_python_preference = only-managed
dependency_groups = testing
set_env =
    COVERAGE_FILE = tests/unit_tests/coverage/.coverage.{envname}
allowlist_externals = npm
commands_pre =
    npm --prefix "source/frontend" install
    npm --prefix "source/frontend" run build
commands =
    python -m pytest \
        --config-file "tests/unit_tests/.pytest.ini" \
        --cov virelay \
        --cov-config "tests/unit_tests/.coveragerc" \
        --cov-append \
        {posargs:tests/unit_tests}

# A test environment that combines the coverage data from all runs of the unit tests with the different Python versions and generates a single report
[testenv:coverage]
set_env =
    COVERAGE_FILE = tests/unit_tests/coverage/.coverage
depends =
    py310
    py311
    py312
    py313
commands_pre =
commands =
    coverage combine \
        --rcfile "tests/unit_tests/.coveragerc"
    coverage report \
        --rcfile "tests/unit_tests/.coveragerc" \
        --show-missing
    coverage html \
        --rcfile "tests/unit_tests/.coveragerc" \
        --directory "tests/unit_tests/coverage/report"

# A test environment that will build the documentation using Sphinx
[testenv:docs]
base_python = py313
dependency_groups = docs
commands_pre =
commands =
    sphinx-build \
        --color \
        --fail-on-warning \
        --fresh-env \
        --keep-going \
        --doctree-dir "docs/doctree" \
        --builder html \
        "docs/source" \
        "docs/build" \
        {posargs}

# A test environment that will run the PyLint linter on the ViRelAy backend, the unit tests, the Sphinx configuration file, and the examples; PyLint
# not only requires the linting dependency group, but also the testing and the docs dependency groups to be installed, because PyLint will try to
# import the packages in the modules its it linting, and the unit tests use the PyTest package and the Sphinx configuration uses the PybTeX and the
# Sphinx packages
[testenv:pylint]
base_python = py313
dependency_groups =
    testing
    linting
    docs
commands_pre =
commands =
    pylint \
        --rcfile="tests/linters/.pylintrc" \
        --output-format="parseable" \
        "source/backend/virelay" \
        "tests/unit_tests" \
        "docs/source/conf.py"
    uv run \
        --no-project \
        --python 3.9.21 \
        --with 'pylint==3.3.6' \
        --with 'zennit==0.5.1' \
        --with 'corelay==0.2.1' \
        --with 'h5py==3.13.0' \
        --with 'pyyaml==6.0.2' \
        pylint \
            --rcfile tests/linters/.pylintrc \
            --disable duplicate-code \
            docs/examples/hdf5_structure.py \
            docs/examples/make_project.py \
            docs/examples/meta_analysis.py \
            docs/examples/test-project/make_test_data.py \
            docs/examples/vgg16-project/explain_vgg.py \
            docs/examples/vgg16-project/make_dataset.py \
            docs/examples/vgg16-project/train_vgg.py

# A test environment that will run the PyCodeStyle linter on the REST API backend, the unit tests, the setup script, and the Sphinx configuration file
[testenv:pycodestyle]
base_python = py313
dependency_groups = linting
commands_pre =
commands =
    pycodestyle \
        --config="tests/linters/.pycodestyle" \
        "source/backend/virelay" \
        "tests/unit_tests" \
        "docs/source/conf.py"
    uv run \
        --no-project \
        --python 3.9.21 \
        --with 'pycodestyle==2.13.0' \
        --with 'zennit==0.5.1' \
        --with 'corelay==0.2.1' \
        --with 'h5py==3.13.0' \
        --with 'pyyaml==6.0.2' \
        pycodestyle \
            --config tests/linters/.pycodestyle \
            docs/examples/hdf5_structure.py \
            docs/examples/make_project.py \
            docs/examples/meta_analysis.py \
            docs/examples/test-project/make_test_data.py \
            docs/examples/vgg16-project/explain_vgg.py \
            docs/examples/vgg16-project/make_dataset.py \
            docs/examples/vgg16-project/train_vgg.py

# A test environment that will run the PyDocLint docstring linter on the REST API backend, the unit tests, the setup script, and the Sphinx
# configuration file
[testenv:pydoclint]
base_python = py313
dependency_groups = linting
commands_pre =
commands =
    pydoclint \
        --config="tests/linters/.pydoclint.toml" \
        "source/backend/virelay" \
        "tests/unit_tests" \
        "docs/source/conf.py"
    uv run \
        --no-project \
        --python 3.9.21 \
        --with 'pydoclint==0.6.4' \
        --with 'zennit==0.5.1' \
        --with 'corelay==0.2.1' \
        --with 'h5py==3.13.0' \
        --with 'pyyaml==6.0.2' \
        pydoclint \
            --config tests/linters/.pydoclint.toml \
            docs/examples/hdf5_structure.py \
            docs/examples/make_project.py \
            docs/examples/meta_analysis.py \
            docs/examples/test-project/make_test_data.py \
            docs/examples/vgg16-project/explain_vgg.py \
            docs/examples/vgg16-project/make_dataset.py \
            docs/examples/vgg16-project/train_vgg.py

# A test environment that will run the MyPy static type checker on the REST API backend, the unit tests, the setup script, and the Sphinx
# configuration file
[testenv:mypy]
base_python = py313
dependency_groups = linting
commands_pre =
commands =
    mypy \
        --config-file="tests/linters/.mypy.ini" \
        "source/backend/virelay" \
        "tests/unit_tests" \
        "docs/source/conf.py"
    uv run \
        --no-project \
        --python 3.9.21 \
        --with 'mypy==1.15.0' \
        --with 'zennit==0.5.1' \
        --with 'corelay==0.2.1' \
        --with 'h5py==3.13.0' \
        --with 'pyyaml==6.0.2' \
        --with 'types-PyYAML==6.0.12.20240917' \
        mypy \
            --config-file tests/linters/.mypy.ini \
            --ignore-missing-imports \
            docs/examples/hdf5_structure.py \
            docs/examples/make_project.py \
            docs/examples/meta_analysis.py \
            docs/examples/test-project/make_test_data.py \
            docs/examples/vgg16-project/explain_vgg.py \
            docs/examples/vgg16-project/make_dataset.py \
            docs/examples/vgg16-project/train_vgg.py
