#!/bin/bash

# Gets the directory that the docker-tox script is located in
DOCKER_TOX_DIRECTORY=$(dirname $(readlink -f $0))

# Checks if the Docker image for Docker tox exists, if not, it is built
if [ -z "$(docker image list --quiet docker-tox:0.1.0 2> /dev/null)" ]; then
    echo "The Docker image for Docker tox could not be found."
    echo "Building Docker image for Docker tox. This can take a couple of minutes..."
    docker build --tag docker-tox:0.1.0 $DOCKER_TOX_DIRECTORY --quiet > /dev/null
fi

# Runs Docker tox as the current user, with the directory containing the repository mounted inside the container; the command line arguments that were
# passed to the script are passed to tox inside the Docker container
docker run \
    --rm \
    --tty \
    --interactive \
    --user $(id --user ${USER}):$(id --group ${USER}) \
    --volume $DOCKER_TOX_DIRECTORY/../..:/opt/virelay:rw \
    docker-tox:0.1.0 \
    "$@"
