name: tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: test ${{matrix.tox_env}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tox_env: py39
            python: "3.9"
          - tox_env: py310
            python: "3.10"
          - tox_env: py311
            python: "3.11"
          - tox_env: py312
            python: "3.12"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install base python for tox
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install tox
        run: python -m pip install tox
      - name: Install python for test
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Setup test environment
        run: tox -vv --notest -e ${{ matrix.tox_env }}
      - name: Run test
        run: tox --skip-pkg-install -e ${{ matrix.tox_env }}

  check:
    name: check ${{ matrix.tox_env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - flake8
          - pylint
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install base python for tox
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install tox
        run: python -m pip install tox
      - name: Setup test environment
        run: tox -vv --notest -e ${{ matrix.tox_env }}
      - name: Run test
        run: tox --skip-pkg-install -e ${{ matrix.tox_env }}

  spell-check:
    name: Spell-Check Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install CSpell
        run: npm install --global git+https://github.com/streetsidesoftware/cspell-cli
      - name: Run Spell Check
        run: npx cspell lint . --config .cspell.json

  docs:
    name: docs
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install base python for tox
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install texlive
        run: sudo apt-get update -y && sudo apt-get install -y texlive texlive-latex-extra dvipng
      - name: Install tox
        run: python -m pip install tox
      - name: Setup test environment
        run: tox -vv --notest -e docs
      - name: Run test
        run: tox --skip-pkg-install -e docs
